# coding: utf-8

"""
    Identity Security Cloud Beta API

    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. These APIs are in beta and are subject to change. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

    The version of the OpenAPI document: 3.1.0-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from sailpoint.beta.models.transform_attributes import TransformAttributes

class TestTransformAttributes(unittest.TestCase):
    """TransformAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransformAttributes:
        """Test TransformAttributes
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransformAttributes`
        """
        model = TransformAttributes()
        if include_optional:
            return TransformAttributes(
                source_name = 'Workday',
                attribute_name = 'DEPARTMENT',
                account_sort_attribute = 'created',
                account_sort_descending = False,
                account_return_first_link = False,
                account_filter = '!(nativeIdentity.startsWith("*DELETED*"))',
                account_property_filter = '(groups.containsAll({'Admin'}) || location == 'Austin')',
                requires_periodic_refresh = False,
                input = {type=accountAttribute, attributes={attributeName=first_name, sourceName=Source}},
                values = 'string$variable',
                expression = 'now+1w',
                positive_condition = 'true',
                negative_condition = 'false',
                first_date = None,
                second_date = None,
                operator = 'LT',
                input_format = None,
                output_format = None,
                round_up = False,
                default_region = 'US',
                ignore_errors = False,
                name = 'email',
                operation = 'getReferenceIdentityAttribute',
                include_numbers = True,
                include_special_chars = True,
                length = '4',
                uid = '2c91808570313110017040b06f344ec9',
                substring = 'admin_',
                format = 'alpha2',
                padding = '0',
                table = {-= , "=', ñ=n},
                id = 'Existing Transform',
                regex = '[^a-zA-Z]',
                replacement = ' ',
                delimiter = ',',
                index = '5',
                throws = True,
                begin = 1,
                begin_offset = 3,
                end = 6,
                end_offset = 1
            )
        else:
            return TransformAttributes(
                source_name = 'Workday',
                attribute_name = 'DEPARTMENT',
                values = 'string$variable',
                expression = 'now+1w',
                positive_condition = 'true',
                negative_condition = 'false',
                first_date = None,
                second_date = None,
                operator = 'LT',
                name = 'email',
                operation = 'getReferenceIdentityAttribute',
                include_numbers = True,
                include_special_chars = True,
                length = '4',
                uid = '2c91808570313110017040b06f344ec9',
                substring = 'admin_',
                table = {-= , "=', ñ=n},
                id = 'Existing Transform',
                regex = '[^a-zA-Z]',
                replacement = ' ',
                delimiter = ',',
                index = '5',
                begin = 1,
        )
        """

    def testTransformAttributes(self):
        """Test TransformAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
