# coding: utf-8

"""
    Identity Security Cloud Beta API

    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. These APIs are in beta and are subject to change. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

    The version of the OpenAPI document: 3.1.0-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from sailpoint.beta.models.iso3166 import ISO3166

class TestISO3166(unittest.TestCase):
    """ISO3166 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ISO3166:
        """Test ISO3166
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ISO3166`
        """
        model = ISO3166()
        if include_optional:
            return ISO3166(
                format = 'alpha2',
                requires_periodic_refresh = False,
                input = {type=accountAttribute, attributes={attributeName=first_name, sourceName=Source}}
            )
        else:
            return ISO3166(
        )
        """

    def testISO3166(self):
        """Test ISO3166"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
