# coding: utf-8

"""
    Identity Security Cloud V3 API

    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from sailpoint.v3.models.rule import Rule

class TestRule(unittest.TestCase):
    """Rule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Rule:
        """Test Rule
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Rule`
        """
        model = Rule()
        if include_optional:
            return Rule(
                name = 'Cloud Services Deployment Utility',
                requires_periodic_refresh = False,
                operation = 'getReferenceIdentityAttribute',
                include_numbers = True,
                include_special_chars = True,
                length = '10',
                uid = '2c91808570313110017040b06f344ec9'
            )
        else:
            return Rule(
                name = 'Cloud Services Deployment Utility',
                operation = 'getReferenceIdentityAttribute',
                include_numbers = True,
                include_special_chars = True,
                length = '10',
                uid = '2c91808570313110017040b06f344ec9',
        )
        """

    def testRule(self):
        """Test Rule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
