# coding: utf-8

"""
    Identity Security Cloud V3 API

    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from sailpoint.v3.models.e164phone import E164phone

class TestE164phone(unittest.TestCase):
    """E164phone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> E164phone:
        """Test E164phone
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `E164phone`
        """
        model = E164phone()
        if include_optional:
            return E164phone(
                default_region = 'US',
                requires_periodic_refresh = False,
                input = {type=accountAttribute, attributes={attributeName=first_name, sourceName=Source}}
            )
        else:
            return E164phone(
        )
        """

    def testE164phone(self):
        """Test E164phone"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
