# coding: utf-8

"""
    Identity Security Cloud V3 API

    Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from sailpoint.v3.models.search_document import SearchDocument

class TestSearchDocument(unittest.TestCase):
    """SearchDocument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchDocument:
        """Test SearchDocument
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchDocument`
        """
        model = SearchDocument()
        if include_optional:
            return SearchDocument(
                id = '2c91808568c529c60168cca6f90c1313',
                name = 'John Doe',
                description = 'The admin role',
                created = '2018-06-25T20:22:28.104Z',
                modified = '2018-06-25T20:22:28.104Z',
                synced = '2018-06-25T20:22:33.104Z',
                enabled = True,
                requestable = True,
                request_comments_required = False,
                owner = sailpoint.v3.models.base_access_all_of_owner.BaseAccess_allOf_owner(
                    type = 'IDENTITY', 
                    id = '2c9180a46faadee4016fb4e018c20639', 
                    name = 'Support', 
                    email = 'cloud-support@sailpoint.com', ),
                type = 'identity',
                source = sailpoint.v3.models.identity_document_all_of_source.IdentityDocument_allOf_source(
                    id = '2c91808b6e9e6fb8016eec1a2b6f7b5f', 
                    name = 'ODS-HR-Employees', ),
                entitlements = [
                    sailpoint.v3.models.base_entitlement.BaseEntitlement(
                        has_permissions = False, 
                        description = 'Cloud engineering', 
                        attribute = 'memberOf', 
                        value = 'CN=Cloud Engineering,DC=sailpoint,DC=COM', 
                        schema = 'group', 
                        privileged = False, 
                        id = '2c918084575812550157589064f33b89', 
                        name = 'CN=Cloud Engineering,DC=sailpoint,DC=COM', )
                    ],
                entitlement_count = 3,
                tags = [TAG_1, TAG_2],
                action = 'update',
                stage = 'Completed',
                origin = '',
                status = 'UNREGISTERED',
                requester = None,
                recipient = None,
                tracking_number = '63f891e0735f4cc8bf1968144a1e7440',
                errors = [
                    ''
                    ],
                warnings = [
                    ''
                    ],
                approvals = [
                    sailpoint.v3.models.approval.Approval(
                        comments = [
                            sailpoint.v3.models.approval_comment.ApprovalComment(
                                comment = 'This request was autoapproved by our automated ETS subscriber.', 
                                commenter = 'Automated AR Approval', 
                                date = '2018-06-25T20:22:28.104Z', )
                            ], 
                        created = '2018-06-25T20:22:28.104Z', 
                        modified = '2018-06-25T20:22:28.104Z', 
                        owner = null, 
                        result = 'Finished', 
                        type = '', )
                    ],
                original_requests = [
                    sailpoint.v3.models.original_request.OriginalRequest(
                        account_id = 'CN=Abby Smith,OU=Austin,OU=Americas,OU=Demo,DC=seri,DC=acme,DC=com', 
                        attribute_requests = [
                            sailpoint.v3.models.attribute_request.AttributeRequest(
                                name = 'groups', 
                                op = 'Add', 
                                value = '3203537556531076', )
                            ], 
                        op = 'add', 
                        source = null, )
                    ],
                expansion_items = [
                    sailpoint.v3.models.expansion_item.ExpansionItem(
                        account_id = '2c91808981f58ea601821c3e93482e6f', 
                        cause = 'Role', 
                        name = 'smartsheet-role', 
                        attribute_requests = [
                            sailpoint.v3.models.attribute_request.AttributeRequest(
                                name = 'groups', 
                                op = 'Add', 
                                value = '3203537556531076', )
                            ], 
                        source = null, )
                    ],
                account_requests = [
                    sailpoint.v3.models.account_request.AccountRequest(
                        account_id = 'John.Doe', 
                        attribute_requests = [
                            sailpoint.v3.models.attribute_request.AttributeRequest(
                                name = 'groups', 
                                op = 'Add', 
                                value = '3203537556531076', )
                            ], 
                        op = 'Modify', 
                        provisioning_target = null, 
                        result = sailpoint.v3.models.account_request_result.AccountRequest_result(
                            errors = [
                                '[ConnectorError] [
  {
    "code": "unrecognized_keys",
    "keys": [
      "groups"
    ],
    "path": [],
    "message": "Unrecognized key(s) in object: 'groups'"
  }
] (requestId: 5e9d6df5-9b1b-47d9-9bf1-dc3a2893299e)'
                                ], 
                            status = 'failed', 
                            ticket_id = '', ), 
                        source = null, )
                    ],
                sources = 'smartsheet-test, airtable-v4, IdentityNow',
                display_name = 'Carol.Adams',
                segments = [
                    sailpoint.v3.models.base_segment.BaseSegment(
                        id = 'b009b6e3-b56d-41d9-8735-cb532ea0b017', 
                        name = 'Test Segment', )
                    ],
                segment_count = 1,
                cloud_governed = False,
                privileged = False,
                identity_count = 3,
                type = 'SYSTEM_CONFIG',
                actor = 'System',
                target = 'Carol.Adams',
                stack = 'tpe',
                ip_address = '52.52.97.85',
                details = '73b65dfbed1842548c207432a18c84b0',
                attributes = {country=US, firstname=Carol, cloudStatus=UNREGISTERED},
                objects = [
                    'AUTHENTICATION'
                    ],
                operation = 'REQUEST',
                technical_name = 'AUTHENTICATION_REQUEST_PASSED',
                first_name = 'Carol',
                last_name = 'Adams',
                email = 'Carol.Adams@sailpointdemo.com',
                phone = '+1 440-527-3672',
                inactive = False,
                protected = False,
                employee_number = '1a2a3d4e',
                manager = sailpoint.v3.models.identity_document_all_of_manager.IdentityDocument_allOf_manager(
                    id = '2c9180867dfe694b017e208e27c05799', 
                    name = 'Amanda.Ross', 
                    display_name = 'Amanda.Ross', ),
                is_manager = False,
                identity_profile = sailpoint.v3.models.identity_document_all_of_identity_profile.IdentityDocument_allOf_identityProfile(
                    id = '3bc8ad26b8664945866b31339d1ff7d2', 
                    name = 'HR Employees', ),
                processing_state = '',
                processing_details = sailpoint.v3.models.processing_details.ProcessingDetails(
                    date = '2018-06-25T20:22:28.104Z', 
                    stage = 'In Process', 
                    retry_count = 0, 
                    stack_trace = '<stack trace>', 
                    message = '<message>', ),
                accounts = [
                    null
                    ],
                account_count = 3,
                apps = [
                    null
                    ],
                app_count = 2,
                access = [
                    null
                    ],
                access_count = 5,
                role_count = 1,
                access_profile_count = 1,
                owns = [
                    sailpoint.v3.models.owns.Owns(
                        sources = [
                            sailpoint.v3.models.reference_1.Reference_1(
                                id = '2c91808568c529c60168cca6f90c1313', 
                                name = 'John Doe', )
                            ], 
                        entitlements = [
                            sailpoint.v3.models.reference_1.Reference_1(
                                id = '2c91808568c529c60168cca6f90c1313', 
                                name = 'John Doe', )
                            ], 
                        access_profiles = [
                            
                            ], 
                        roles = [
                            
                            ], 
                        apps = [
                            
                            ], 
                        governance_groups = [
                            
                            ], 
                        fallback_approver = False, )
                    ],
                owns_count = 5,
                access_profiles = [
                    sailpoint.v3.models.base_access_profile.BaseAccessProfile(
                        id = '2c91809c6faade77016fb4f0b63407ae', 
                        name = 'Admin Access', )
                    ]
            )
        else:
            return SearchDocument(
                id = '2c91808568c529c60168cca6f90c1313',
                name = 'John Doe',
                type = 'identity',
        )
        """

    def testSearchDocument(self):
        """Test SearchDocument"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
